version: "3.9"

services:
  # --- Main Database ---
  postgres-db:
    image: ankane/pgvector:latest
    container_name: postgres-db-container
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${POSTGRES_USER_MAIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_MAIN}
      POSTGRES_DB: ${POSTGRES_DB_MAIN}
    ports:
      - "${POSTGRES_PORT_MAIN}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/main:/docker-entrypoint-initdb.d   # <--- added
    networks:
      - app-network
    restart: always

  # --- Admin Panel Database ---
  postgres-admin:
    image: ankane/pgvector:latest
    container_name: postgres-admin-container
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${POSTGRES_USER_ADMIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ADMIN}
      POSTGRES_DB: ${POSTGRES_DB_ADMIN}
    ports:
      - "${POSTGRES_PORT_ADMIN}:5432"
    volumes:
      - postgres_admin_data:/var/lib/postgresql/data
      - ./init-scripts/admin:/docker-entrypoint-initdb.d   # <--- added
    networks:
      - app-network
    restart: always

  # --- pgAdmin ---
  pgadmin-server:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-server-container
    platform: linux/amd64
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - app-network
    depends_on:
      - postgres-db
      - postgres-admin
    restart: always
    
  # --- Flyway ---
  flyway:
    image: flyway/flyway:latest
    container_name: flyway-migration
    platform: linux/amd64
    depends_on:
      - postgres-db
    volumes:
      - ./sql/migrations:/flyway/sql
    command: >
      -connectRetries=10
      -url=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB_MAIN}
      -user=${FLYWAY_USER}
      -password=${FLYWAY_PASSWORD}
      migrate
    networks:
      - app-network

volumes:
  postgres_data:
  postgres_admin_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
