services:
  # --- Database Service ---
  postgres-db:
    image: postgres:latest
    container_name: postgres-db-container
    platform: linux/arm64
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT_SECONDARY}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always


  # --- Management Tool ---
  pgadmin-server:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-server-container
    platform: linux/arm64
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT_SECONDARY}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - postgres-db
    restart: always

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge