CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE ai_product_embeddings (
    product_id BIGINT PRIMARY KEY,
    embedding VECTOR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);